name: dfc_dart
description: Dart Utils.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^6.0.0
  lint: ^1.5.3
