name: dfc_dart
description: Dart Utils.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.7
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.1.3
