name: dfc_dart
description: Dart Utils.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  path: ^1.8.1

dev_dependencies:
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics: ^4.15.2
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
