name: dfc_dart
description: Dart Utils.
version: 1.0.1
homepage: distantfutu.re
publish_to: "none"

environment:
  sdk: ">=3.1.6 <4.0.0"

dependencies:
  mime: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/paulkastel/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
